### ISSUE TITLE
hrisey plugin crashes lombok plugin if they are both installed.

### ISSUE THREAD

**Issue by ScottPierce** [mg6maciej/hrisey-intellij-plugin#1]
Every time I open Intellij 13 with hrisey installed, lombok crashes with the following error forcing me to disable it:

Plugin 'Lombook Plugin' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key de.plushnikov.intellij.plugin.LombokLoader duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:142)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.registerComponent(AbstractDelegatingMutablePicoContainer.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:416)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:398)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:384)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:107)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:87)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:508)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:151)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:58)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

This is fairly annoying. I'd like to use hrisey on Android, but I also have java specific projects I need to be able to continue to use Lombok on.

**Comment by mg6maciej** [comment]
Do you mean having both hrisey-intellij-plugin and lombok-intellij-plugin installed? I'm not sure how would they co-exist. They would probably both add the same methods and classes twice, showing strange results in IDE.  
I try to keep up with lombok plugin and update this fork. Looking at upstream, I'm behind by a couple of commits and will update after resolving the issues with JDK 8 first.

**Comment by ScottPierce** [comment]
Will it be directly compatible with non-android projects? That would allow me to remove lombok, and only use hrisey I suppose.

**Comment by mg6maciej** [comment]
Yes, it should cause no problems. I have a pull request waiting in lombok-intellij-plugin, cause I didn't want to have a separate plugin. I decided to create it because of slow response.

**Comment by ScottPierce** [comment]
Makes sense to me.
